name: CI - Ubuntu 26.04

permissions:
  contents: read

on:
  # push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt install -y cmake ninja-build build-essential kwin-dev extra-cmake-modules libkf6globalaccel-dev libkf6i18n-dev pkgconf libdrm-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPROJECT_VERSION_SUFFIX=CI

      - name: Build
        run: cmake --build build --parallel

      - name: Packaging
        run: cd build && cpack -G DEB

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: kwin-effect-scale-to-screen-${{ github.sha }}
          path: build/cpack_artifacts/*.deb
